// Reproducible subset of Source Han Sans SC Medium (SIL Open Font License 1.1).
// node tools/prepare_toolkit_font.cjs /path/to/SourceHanSansSC-Medium.otf /path/to/lv_font_conv.js
const fs = require('node:fs');
const path = require('node:path');
const cp = require('node:child_process');
const root = path.resolve(__dirname, '..');
const [font, converter] = process.argv.slice(2);
if (!font || !converter) throw new Error('Supply Source Han Sans SC Medium and lv_font_conv.js paths');
const files = ['main/toolkit_model.c', 'main/toolkit_view.c', 'main/toolkit_main.c'];
const chars = [...new Set(files.map(f => fs.readFileSync(path.join(root, f), 'utf8')).join('').match(/[\u3000-\u9fff\uff00-\uffef…·]/gu))].sort().join('');
fs.mkdirSync(path.join(root, 'assets/fonts'), {recursive: true});
cp.execFileSync(process.execPath, [converter, '--font', font, '--size', '16', '--bpp', '4', '--format', 'lvgl', '--lv-include', 'lvgl.h', '--no-compress', '--range', '0x20-0x7e', '--symbols', chars, '--lv-font-name', 'toolkit_font_16', '-o', path.join(root, 'assets/fonts/toolkit_font_16.c')], {stdio: 'inherit'});
// Keep generated metadata reproducible and do not embed the builder's local paths.
const output = path.join(root, 'assets/fonts/toolkit_font_16.c');
fs.writeFileSync(output, fs.readFileSync(output, 'utf8').replace(/^ \* Opts:.*$/m,
  ' * Generated by tools/prepare_toolkit_font.cjs. SIL OFL 1.1; see toolkit-font-LICENSE.txt.').trimEnd() + '\n');
