#!/usr/bin/env python3
"""Compile the approved 3:4 cover into a flash-resident RGB565 LVGL image.

Requires Pillow. Run from any directory; original artwork is never overwritten.
"""
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
source = root / 'assets/images/niuma/community-cover-v1.png'
output = root / 'assets/images/niuma/niuma_cover.c'
with Image.open(source) as original:
    assert original.width * 4 == original.height * 3, 'Cover must be portrait 3:4'
    image = original.convert('RGB').resize((240, 320), Image.Resampling.LANCZOS)
pixels = []
for r, g, b in image.getdata():
    value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    pixels.extend((value & 255, value >> 8))
lines = ['/* Generated by tools/prepare_niuma_cover.py; do not edit. */',
         '#include "lvgl.h"', 'static const uint8_t cover_pixels[] = {']
lines += ['    ' + ','.join(f'0x{v:02x}' for v in pixels[i:i+24]) + ','
          for i in range(0, len(pixels), 24)]
lines += ['};', 'const lv_image_dsc_t niuma_cover = {',
          '    .header = {.magic=LV_IMAGE_HEADER_MAGIC, .cf=LV_COLOR_FORMAT_RGB565,',
          '               .w=240, .h=320, .stride=480},',
          '    .data_size=sizeof(cover_pixels), .data=cover_pixels,', '};', '']
output.write_text('\n'.join(lines))
print(f'{output}: {len(pixels)} bytes in flash, no full-screen RAM buffer')
